
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return knex('products').insert([
        {"name": 'Ornate Heart Pendant', "photo": 'https://images.unsplash.com/photo-1486821416551-68a65ef4d618?auto=format&fit=crop&w=1050&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Urban Outfitters", "sizes": "one size", "description": "Hand-crafted heart pendant. Each one is unique.", "price": 35.00, "commission": 5.00, "on_sale": false, "limited_time": true, "handmade": false, "ethical": true},
        {"name": 'Chenile Sweater', "photo": 'https://images.unsplash.com/photo-1505364770813-949f7f90cf08?auto=format&fit=crop&w=1050&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Patagonia", "sizes": "small, med, large", "description": "Cozy pink sweater. Made in the USA.", "price": 19.99, "commission": 1.99, "on_sale": false, "limited_time": false, "handmade": true, "ethical": true},
        {"name": 'Denim Leggings', "photo": 'https://images.unsplash.com/photo-1416838375725-e834a83f62b7?auto=format&fit=crop&w=1052&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"J. Crew", "sizes": "small, med, large", "description": "Fitted denim color leggings.", "price": 24.99, "commission": 3.99, "on_sale": true, "limited_time": false, "handmade": false, "ethical": true},
        {"name": 'Tie and Pocket Square', "photo": 'https://images.unsplash.com/photo-1502148589715-3f209594d750?dpr=1&auto=format&fit=crop&w=1000&q=80&cs=tinysrgb&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Banana Republic", "sizes": "one size", "description": "Silk tie and matching pocket square sold as a set.", "price": 55.95, "commission": 10.00, "on_sale": true, "limited_time": true, "handmade": false, "ethical": true},
        {"name": 'Pink Lacy Skirt', "photo": 'https://images.unsplash.com/photo-1484328256245-34b71758c30b?dpr=1&auto=format&fit=crop&w=1000&q=80&cs=tinysrgb&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Dillards", "sizes": "small, med, large", "description": "Versatile pink skirt. Machine washable cotton.", "price": 29.99, "commission": 3.00, "on_sale": true, "limited_time": false, "handmade": false, "ethical": true},
        {"name": 'Silk Pashmina', "photo": 'https://images.unsplash.com/photo-1465199549974-7d82de6e2830?auto=format&fit=crop&w=1489&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Banana Republic", "sizes": "one size", "description": "Soft silk pashmina in a variety of colors - measures 24 by 40 inches", "price": 49.99, "commission": 8.00, "on_sale": true, "limited_time": false, "handmade": true, "ethical": true},
        {"name": 'Hat and Mittens Set', "photo": 'https://images.unsplash.com/photo-1452689842785-5f14840dca48?auto=format&fit=crop&w=700&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Patagonia", "sizes": "small, med, large", "description": "Cozy wool hat and mittens. Made in the USA.", "price": 24.99, "commission": 5.00, "on_sale": true, "limited_time": false, "handmade": false, "ethical": true},
        {"name": 'Mens Dress Shoes', "photo": 'https://images.unsplash.com/photo-1466699189113-a3b204834b96?auto=format&fit=crop&w=1490&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Banana Republic", "sizes": "small, med, large", "description": "Fine leather - available in a variety of colors and sizes.", "price": 79.99, "commission": 15.00, "on_sale": true, "limited_time": false, "handmade": true, "ethical": false},
        {"name": 'Leather Purse', "photo": 'https://images.unsplash.com/photo-1484527273420-c598cb0601f8?auto=format&fit=crop&w=1050&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Banana Republic", "sizes": "one size", "description": "Genuine leather - available in brown, black, red, and navy.", "price": 65.00, "commission": 10.00, "on_sale": true, "limited_time": true, "handmade": false, "ethical": false},
        {"name": 'Mans Analog Watch', "photo": 'https://images.unsplash.com/photo-1492611772339-c581bbfb4dee?auto=format&fit=crop&w=1050&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D',"seller":"Dillards", "sizes": "one size", "description": "High quality mans watch. 10 year warranty included.", "price": 65.00, "commission": 12.00, "on_sale": false, "limited_time": false, "handmade": true, "ethical": true}
      ]);
    });
};
